"""add task status index

Revision ID: 7bc00185540b
Revises: 9c6b77913981
Create Date: 2026-09-23 22:49:54.970718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bc00185540b'
down_revision: Union[str, None] = '9c6b77913981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_status_created_at', 'tasks', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_created_at', table_name='tasks')
    # ### end Alembic commands ###
