"""create task tables

Revision ID: 9c6b77913981
Revises: 081dac081be9
Create Date: 2026-09-23 22:36:55.166118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c6b77913981'
down_revision: Union[str, None] = '081dac081be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
